In [ ]:
import numpy as np
import pandas as pd
import os

import tensorflow as tf
import tensorflow.keras as keras
from tensorflow.keras import layers

from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.callbacks import ReduceLROnPlateau
from tensorflow.keras.callbacks import ModelCheckpoint

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

print("All libraries imported successfully!")

All libraries imported successfully!

In [ ]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (1.7.4.5)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2026.1.4)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.4.4)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.11)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.5.1)

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
!kaggle competitions list

ref                                                                                 deadline             category                reward  teamCount  userHasEntered
----------------------------------------------------------------------------------  -------------------  ---------------  -------------  ---------  --------------
https://www.kaggle.com/competitions/ai-mathematical-olympiad-progress-prize-3       2026-04-15 23:59:00  Featured         2,207,152 Usd       2295           False
https://www.kaggle.com/competitions/vesuvius-challenge-surface-detection            2026-02-27 23:59:00  Research           200,000 Usd       1351           False
https://www.kaggle.com/competitions/stanford-rna-3d-folding-2                       2026-03-25 23:59:00  Featured           100,000 Usd        898           False
https://www.kaggle.com/competitions/med-gemma-impact-challenge                      2026-02-24 23:59:00  Featured           100,000 Usd        138           False
https://www.kaggle.com/competitions/deep-past-initiative-machine-translation        2026-03-23 23:59:00  Featured            50,000 Usd       1928           False
https://www.kaggle.com/competitions/playground-series-s6e2                          2026-02-28 23:59:00  Playground               Kudos       2482           False
https://www.kaggle.com/competitions/titanic                                         2030-01-01 00:00:00  Getting Started      Knowledge      12241           False
https://www.kaggle.com/competitions/home-data-for-ml-course                         2030-01-01 23:59:00  Getting Started      Knowledge       4395           False
https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques     2030-01-01 00:00:00  Getting Started      Knowledge       4213           False
https://www.kaggle.com/competitions/spaceship-titanic                               2030-01-01 00:00:00  Getting Started      Knowledge       2056           False
https://www.kaggle.com/competitions/digit-recognizer                                2030-01-01 00:00:00  Getting Started      Knowledge        850           False
https://www.kaggle.com/competitions/store-sales-time-series-forecasting             2030-06-30 23:59:00  Getting Started      Knowledge        755           False
https://www.kaggle.com/competitions/nlp-getting-started                             2030-01-01 00:00:00  Getting Started      Knowledge        492           False
https://www.kaggle.com/competitions/llm-classification-finetuning                   2030-07-01 23:59:00  Getting Started      Knowledge        245           False
https://www.kaggle.com/competitions/connectx                                        2030-01-01 00:00:00  Getting Started      Knowledge        212           False
https://www.kaggle.com/competitions/tpu-getting-started                             2030-06-03 23:59:00  Getting Started      Knowledge        146           False
https://www.kaggle.com/competitions/gan-getting-started                             2030-07-01 23:59:00  Getting Started      Knowledge         57           False
https://www.kaggle.com/competitions/contradictory-my-dear-watson                    2030-07-01 23:59:00  Getting Started      Knowledge         20           False
https://www.kaggle.com/competitions/hull-tactical-market-prediction                 2026-06-16 23:59:00  Featured           100,000 Usd       3677           False
https://www.kaggle.com/competitions/recodai-luc-scientific-image-forgery-detection  2026-05-06 23:59:00  Research            55,000 Usd       1564           False

In [ ]:
!kaggle competitions download -c landmark-recognition-2021

403 Client Error: Forbidden for url: https://www.kaggle.com/api/v1/competitions/data/download-all/landmark-recognition-2021

In [ ]:
!kaggle competitions download -c landmark-recognition-2021

^C

In [ ]:
!kaggle competitions download -c landmark-recognition-2021 -f sample_submission.csv

Downloading sample_submission.csv to /content
  0% 0.00/293k [00:00<?, ?B/s]
100% 293k/293k [00:00<00:00, 295MB/s]

In [ ]:
!kaggle competitions download -c landmark-recognition-2021 -f train.csv

Downloading train.csv to /content
  0% 0.00/16.8M [00:00<?, ?B/s]
100% 16.8M/16.8M [00:00<00:00, 1.12GB/s]

In [ ]:
import pandas as pd

train_df = pd.read_csv("train.csv")
train_df.head()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 11: invalid start byte

In [ ]:
import pandas as pd

train_df = pd.read_csv("train.csv", encoding="latin-1")
train_df.head()

ParserError: Error tokenizing data. C error: Expected 1 fields in line 4, saw 2

In [ ]:
!unzip -o train.csv.zip

unzip:  cannot find or open train.csv.zip, train.csv.zip.zip or train.csv.zip.ZIP.

In [ ]:
!ls -lh

total 18M
-rw-r--r-- 1 root root   76 Feb 14 04:22 kaggle.json
drwxr-xr-x 1 root root 4.0K Jan 16 14:24 sample_data
-rw-r--r-- 1 root root 293K Aug  4  2021 sample_submission.csv
-rw-r--r-- 1 root root  17M Aug  4  2021 train.csv

In [ ]:
import pandas as pd

train_df = pd.read_csv("train.csv", engine="python")
train_df.head()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 11: invalid start byte

In [ ]:
import pandas as pd

train_df = pd.read_csv("train.csv", encoding="ISO-8859-1")
train_df.head()

ParserError: Error tokenizing data. C error: Expected 1 fields in line 4, saw 2

In [ ]:
!head -5 train.csv

h��Wj����y_ܻ�ʯ�uzwM�}j^+���^5;5⌐c���ܧ��uNY��sv*s�����_+��˴x�pKX��϶G+muJ�c�����a)ǸN�3�Q�}ت}�k����R_��z��yy����{(��Mg�n�:���Rݻ���x�4П�Bl��{JXw�����>��o���!��5���r�x������O��8)[���J���%��}k+�ޞ�a=�R�#W�������ez�ҽ�=�ޥw���E~���]x1��#$l:ZK���a���a֘nv!�P�憧�{]��~?�z��Rϱ{aLn��ܱ�2�����|�%ѯ�a��<}h�,e
�g/�"�b�k3�xP����-2�7Kw�����2y��ܩf��q��jVލI�߱�G�x����9����K`<V����0F+/�dfa�a��7�)㵱������D�f.dae�	��.��{F��U�����x�g(k󀞏��4��û��}.�=w�`P�g�T��V�Ę]q���S�+�5h}����R��0wԄ������_�냡ȓ�HsV���}�G�_>��~btIs17�𧥅c�˹1v\V|X�x�����{D�e�5Vu�	LXxX�5�B
Dj�YX�)����x�����Қp	��-׵0�1O>�g��w/5�\�I�>�q����ܯW}P�Y���BM���a��\&��k`�zb�?����}�>������څ�}�{��B��!t��{� �yw�U���[X��3CR�X)/�O.O��چ�Wx�q�WU?��ȫ���e"߈o��|p���gFL�y^=��fn"a�u	s��!��*1��b9���и��'��� �\Ԋ�a����Ը�z��¢�8��l��d-�U18�|�a-e� �w����w	���b5��0]׶k��X����H���<t��D<O�⇃��ރ(�P]�'�#���?��z�ðz�pΙ���L�\���$>��o]�c��<�Fw��;��ć���Nx�P־ޙ�]��ðɐ�Rx&����9q��pr�9b�cl�ĸ��<v~ع9�J��Īi�u��y'�'z�#a��6�yE��Q)ӂ��ϵ�רq����0�W�Ķ����s�:�D��v�a0�Lte�w����H,��n�VG��L����]X[�ni�3�Ƽ��}�B�CS_s����5���Yĩh؁Q���A��=#��[�G����P	��e���06�z�fL�O�k��>�' �#@|�7��K!'p~��o������F�
��m�=p�x���9�AP�,��&�{�����Չ;>��}wYD�a]4}�����9��98�Z�}���0��{
���M��'���8�a(Rh����ݞ��T�=�U�7ɡ9�͗�ׇ�K3��8��99����̷�L=я�����3��!nQ�^Lǰ	5��

In [ ]:
!file train.csv

train.csv: Zip archive data, at least v4.5 to extract, compression method=deflate

In [ ]:
!mv train.csv train.zip
!unzip train.zip

Archive:  train.zip
  inflating: train.csv

In [1]:
!mkdir -p ~/.kaggle

In [2]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"guruvaishnaviindia09","key":"4dcf27c30182898185bdd6548abf2931"}'}

In [3]:
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [4]:
!kaggle competitions list

401 Client Error: Unauthorized for url: https://www.kaggle.com/api/v1/competitions/list?page=1

In [1]:
!mkdir -p ~/.kaggle

In [2]:
from google.colab import files
files.upload()

Saving kaggle (1).json to kaggle (1).json

{'kaggle (1).json': b'{"username":"guruvaishnaviindia09","key":"9787ac7c43316e98bf157c27ab6190fe"}'}

In [3]:
!mv kaggle\ \(1\).json ~/.kaggle/kaggle.json
!chmod 600 ~/.kaggle/kaggle.json

In [4]:
!kaggle competitions list

ref                                                                                 deadline             category                reward  teamCount  userHasEntered
----------------------------------------------------------------------------------  -------------------  ---------------  -------------  ---------  --------------
https://www.kaggle.com/competitions/ai-mathematical-olympiad-progress-prize-3       2026-04-15 23:59:00  Featured         2,207,152 Usd       2395           False
https://www.kaggle.com/competitions/vesuvius-challenge-surface-detection            2026-02-27 23:59:00  Research           200,000 Usd       1372           False
https://www.kaggle.com/competitions/stanford-rna-3d-folding-2                       2026-03-25 23:59:00  Featured           100,000 Usd        998           False
https://www.kaggle.com/competitions/med-gemma-impact-challenge                      2026-02-24 23:59:00  Featured           100,000 Usd        200           False
https://www.kaggle.com/competitions/deep-past-initiative-machine-translation        2026-03-23 23:59:00  Featured            50,000 Usd       2077           False
https://www.kaggle.com/competitions/playground-series-s6e2                          2026-02-28 23:59:00  Playground               Kudos       3172           False
https://www.kaggle.com/competitions/titanic                                         2030-01-01 00:00:00  Getting Started      Knowledge      11818           False
https://www.kaggle.com/competitions/home-data-for-ml-course                         2030-01-01 23:59:00  Getting Started      Knowledge       4367           False
https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques     2030-01-01 00:00:00  Getting Started      Knowledge       3914           False
https://www.kaggle.com/competitions/spaceship-titanic                               2030-01-01 00:00:00  Getting Started      Knowledge       1996           False
https://www.kaggle.com/competitions/digit-recognizer                                2030-01-01 00:00:00  Getting Started      Knowledge        879           False
https://www.kaggle.com/competitions/store-sales-time-series-forecasting             2030-06-30 23:59:00  Getting Started      Knowledge        715           False
https://www.kaggle.com/competitions/nlp-getting-started                             2030-01-01 00:00:00  Getting Started      Knowledge        465           False
https://www.kaggle.com/competitions/llm-classification-finetuning                   2030-07-01 23:59:00  Getting Started      Knowledge        227           False
https://www.kaggle.com/competitions/connectx                                        2030-01-01 00:00:00  Getting Started      Knowledge        200           False
https://www.kaggle.com/competitions/tpu-getting-started                             2030-06-03 23:59:00  Getting Started      Knowledge        111           False
https://www.kaggle.com/competitions/gan-getting-started                             2030-07-01 23:59:00  Getting Started      Knowledge         49           False
https://www.kaggle.com/competitions/contradictory-my-dear-watson                    2030-07-01 23:59:00  Getting Started      Knowledge         20           False
https://www.kaggle.com/competitions/hull-tactical-market-prediction                 2026-06-16 23:59:00  Featured           100,000 Usd       3677           False
https://www.kaggle.com/competitions/recodai-luc-scientific-image-forgery-detection  2026-05-06 23:59:00  Research            55,000 Usd       1564           False

In [5]:
sample_df = train_df.sample(5000, random_state=42)
sample_df.shape

NameError: name 'train_df' is not defined

In [6]:
import pandas as pd

train_df = pd.read_csv("train.csv")
train_df.shape

FileNotFoundError: [Errno 2] No such file or directory: 'train.csv'

In [7]:
!kaggle competitions download -c landmark-recognition-2021 -f train.csv

Downloading train.csv to /content
  0% 0.00/16.8M [00:00<?, ?B/s]
100% 16.8M/16.8M [00:00<00:00, 1.31GB/s]

In [8]:
!unzip train.csv.zip

unzip:  cannot find or open train.csv.zip, train.csv.zip.zip or train.csv.zip.ZIP.

In [9]:
!ls -lh

total 17M
drwxr-xr-x 1 root root 4.0K Jan 16 14:24 sample_data
-rw-r--r-- 1 root root  17M Aug  4  2021 train.csv

In [10]:
import pandas as pd

train_df = pd.read_csv("train.csv")
train_df.shape

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 11: invalid start byte

In [11]:
train_df = pd.read_csv("train.csv", compression="zip")
train_df.shape

(1580470, 2)

In [12]:
sample_df = train_df.sample(5000, random_state=42)
sample_df.shape

(5000, 2)

In [13]:
sample_df["landmark_id"].nunique()

4445

In [14]:
sample_df["landmark_id"].value_counts().head()

landmark_id
138982    24
126637    13
190822     5
20120      5
127516     5
Name: count, dtype: int64

In [15]:
top_classes = sample_df["landmark_id"].value_counts().head(20).index

filtered_df = sample_df[sample_df["landmark_id"].isin(top_classes)]

filtered_df.shape

(114, 2)

In [16]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
filtered_df["label"] = le.fit_transform(filtered_df["landmark_id"])

filtered_df.head()

/tmp/ipython-input-661390819.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df["label"] = le.fit_transform(filtered_df["landmark_id"])

                       id  landmark_id  label
1333936  0e2390e9f5238cd6       171683     14
1507832  ccd388d42ad071c2       193550     19
1333990  2ac49041d97d2218       171683     14
1278275  e384a54ceb26fe81       164705     12
449824   8b246d871e3d627c        57015      4

In [17]:
from sklearn.model_selection import train_test_split

train_df, val_df = train_test_split(
    filtered_df,
    test_size=0.2,
    random_state=42,
    stratify=filtered_df["label"]
)

print("Train shape:", train_df.shape)
print("Validation shape:", val_df.shape)

Train shape: (91, 3)
Validation shape: (23, 3)

In [19]:
!ls /content

sample_data  train.csv

In [20]:
!kaggle competitions download -c landmark-recognition-2021 -f train_images.zip --quiet

404 Client Error: Not Found for url: https://www.kaggle.com/api/v1/competitions/data/download/landmark-recognition-2021/train_images.zip

In [21]:
filtered_df["image_path"] = "/content/train/" + filtered_df["id"] + ".jpg"
filtered_df.head()

/tmp/ipython-input-2273979645.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df["image_path"] = "/content/train/" + filtered_df["id"] + ".jpg"

,id,landmark_id,label,image_path
1333936,0e2390e9f5238cd6,171683,14,/content/train/0e2390e9f5238cd6.jpg
1507832,ccd388d42ad071c2,193550,19,/content/train/ccd388d42ad071c2.jpg
1333990,2ac49041d97d2218,171683,14,/content/train/2ac49041d97d2218.jpg
1278275,e384a54ceb26fe81,164705,12,/content/train/e384a54ceb26fe81.jpg
449824,8b246d871e3d627c,57015,4,/content/train/8b246d871e3d627c.jpg

In [22]:
import tensorflow as tf
from tensorflow.keras import layers, models

num_classes = filtered_df["label"].nunique()

model = models.Sequential([
    layers.Input(shape=(224, 224, 3)),
    layers.Conv2D(32, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(num_classes, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 222, 222, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 111, 111, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 109, 109, 64)   │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 54, 54, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 186624)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │    23,888,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 20)             │         2,580 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 23,909,972 (91.21 MB)

 Trainable params: 23,909,972 (91.21 MB)

 Non-trainable params: 0 (0.00 B)

In [23]:
import numpy as np

# Create dummy image data
X_train = np.random.rand(len(train_df), 224, 224, 3)
X_val = np.random.rand(len(val_df), 224, 224, 3)

y_train = train_df["label"].values
y_val = val_df["label"].values

history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=3,
    batch_size=8
)

Epoch 1/3
12/12 ━━━━━━━━━━━━━━━━━━━━ 13s 908ms/step - accuracy: 0.0679 - loss: 15.9069 - val_accuracy: 0.0870 - val_loss: 3.0198
Epoch 2/3
12/12 ━━━━━━━━━━━━━━━━━━━━ 10s 799ms/step - accuracy: 0.1575 - loss: 2.9881 - val_accuracy: 0.0870 - val_loss: 2.9940
Epoch 3/3
12/12 ━━━━━━━━━━━━━━━━━━━━ 11s 878ms/step - accuracy: 0.1474 - loss: 2.9912 - val_accuracy: 0.2174 - val_loss: 2.8803

In [24]:
model.evaluate(X_val, y_val)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 757ms/step - accuracy: 0.2174 - loss: 2.8803

[2.880340576171875, 0.21739129722118378]

In [25]:
model.predict(X_val[:5])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 189ms/step

array([[0.04232167, 0.03659871, 0.04674279, 0.0497758 , 0.04623035,
        0.05289517, 0.0367883 , 0.04709226, 0.06472023, 0.05192642,
        0.10479883, 0.05909184, 0.03637113, 0.03993168, 0.03642564,
        0.04806188, 0.03931938, 0.05151791, 0.07645589, 0.03293415],
       [0.04257917, 0.03694185, 0.04749613, 0.04982093, 0.04625146,
        0.05269988, 0.03678076, 0.04714702, 0.06456617, 0.05244819,
        0.10438057, 0.05820142, 0.03621969, 0.04030234, 0.03684458,
        0.0482908 , 0.0390873 , 0.05114926, 0.0753765 , 0.03341601],
       [0.04215916, 0.03655256, 0.04761511, 0.04952681, 0.04596229,
        0.0528632 , 0.03627293, 0.04707512, 0.06467549, 0.05270754,
        0.10622127, 0.05843121, 0.03576431, 0.04003633, 0.03636817,
        0.047998  , 0.03917842, 0.05126077, 0.07650554, 0.03282575],
       [0.04159022, 0.03672775, 0.04730662, 0.05025141, 0.0461224 ,
        0.0524911 , 0.03636929, 0.04706154, 0.0651283 , 0.05268126,
        0.10523237, 0.05840494, 0.03575059, 0.04045261, 0.03624742,
        0.04802711, 0.03931602, 0.05145873, 0.07623449, 0.03314584],
       [0.04228742, 0.037122  , 0.04726987, 0.05004998, 0.04662165,
        0.05238257, 0.03698191, 0.04672944, 0.06481118, 0.05213096,
        0.10315306, 0.05855398, 0.03635929, 0.04067022, 0.0365821 ,
        0.04810023, 0.03990378, 0.05142771, 0.07531998, 0.03354264]],
      dtype=float32)